//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Invoice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoiceitem()
        {
            this.invoices = new HashSet<invoice>();
            this.invoicefiles = new HashSet<invoicefile>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> billing_item_id { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> totalcost { get; set; }
        public Nullable<decimal> taxes { get; set; }
    
        public virtual billingitem billingitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicefile> invoicefiles { get; set; }
    }
}
