//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Invoice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicefile
    {
        public int id { get; set; }
        public string name { get; set; }
        public string filelocation { get; set; }
        public Nullable<System.Guid> invoice_item_id { get; set; }
    
        public virtual invoiceitem invoiceitem { get; set; }
    }
}
